on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

name: Check

jobs:
  run-tests:
    name: Run tests - Python ${{ matrix.py }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.9"
          - "3.8"
          - "3.7"
          - "3.6"
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install . pytest
      - name: Run tests
        run: pytest --color=yes
